### PR TITLE
Updated sl.po

### PR DESCRIPTION
**Pull request by urmatej**
A bit of polishing ...

### CODE REVIEW

**Comment by urmatej** [comment]
There are a few strings in UI not available in translation ...

**Comment by Schneegans** [comment]
Thank you! which strings are not available?

**Comment by urmatej** [comment]
Text:
- Indulge in nostalgia ...
- Transition time ... (3x) with tips. (Do you need screenshots?)

BTW, great extension! Really functional, not only nostalgic ;).
Best,
Matej

**Comment by Schneegans** [comment]
The "Indulge..." text comes from the `metadata.json` and cannot be translated in any extension AFAIK. The transition time sliders got removed when porting the extension to GNOME 45. The translation templates are generated from the `main` branch (which targets GNOME 45) and hence the texts are not translatable anymore. This is not ideal, but else we would need to maintain two different sets of translations...

**Comment by urmatej** [comment]
Yes, I see now. https://discourse.gnome.org/t/is-there-a-way-to-translate-extension-metadata-eg-name-and-description/16353. It is strange, as I would then expect gnome-extension to take care of that.
Thanks!

**Pull request merged**
