### PR TITLE
:globe_with_meridians: Add arabic translations

### PR DESCRIPTION
**Pull request by amrosolaiman**

### CODE REVIEW

**Comment by Schneegans** [comment]
Thanks a lot! Let's see whether this gets imported properly in [Weblate](https://hosted.weblate.org/projects/desktop-cube/core/) :D

**Comment by amrosolaiman** [comment]
You are welcome! I just noticed there wer very small typos. I corrected them now. Should I make a new pull request?

**Comment by Schneegans** [comment]
Yes, you can just create a new pull request. If you want, you can also use Weblate! This shows some warnings, for example you have a double-space somewhere, a missing full stop somewhere else.

**Comment by amrosolaiman** [comment]
Yeah I checked it, and I saw the warnings. Those are the things I corrected. I will try to see how comfortable is it for me for the next translation.

**Comment by amrosolaiman** [comment]
Btw, can you explain me better what do you mean by "You cannot loop around in GNOME Shell anyways" so I can translate it properly?

**Comment by Schneegans** [comment]
Maybe "You cannot switch from the last to the first workspace anyways" would have been a better line. Maybe I should change this... This is not possible in GNOME Shell, so adding a gap between the last and the first workspace makes this more apparent.

**Comment by amrosolaiman** [comment]
I got it now! Should I change it to that meaning or shall I wait a bit?
Consider that now I'm working on the italian translation, so I'm keeping that line empty for now.

**Comment by Schneegans** [comment]
I just changed the line. If you pull the latest `main`, you'll get the updated template. It is also live on Weblate!

**Comment by amrosolaiman** [comment]
Ok. I'm working on them now. I will make a pull request as soon as I finish!

**Pull request merged**
